apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.notification.service.name }}
  labels:
    name: {{ .Values.notification.service.name }}
spec:
  type: {{ .Values.notification.service.type }}
  ports:
    - port: {{ .Values.notification.service.port }}
      targetPort: http
      nodePort: {{ .Values.notification.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    name: "{{ .Values.notification.pod.name }}{{ .Values.image.number}}"
